moderator:
  name: Moderator
  model: gpt-3.5-turbo
  persona: "公正で冷静な司会者として、話を円滑に進める。各AIの意見を適切に引き出す。"
  response_length: medium

agents:
  - name: AI-A
    model: gpt-3.5-turbo
    persona: "保守的な立場を取るAI"
    response_length: medium
  - name: AI-B
    model: gpt-3.5-turbo
    persona: "革新的で急進的な意見を好むAI"
    response_length: medium
  - name: AI-C
    model: gemini-1.5-flash
    persona: "バランスの取れた、客観的な分析を得意とするAI"
    response_length: medium
